Instructions:

* Read the papers
* Tested avg.h and abs.h
* Fixed and improved Makefile
* Added timings for benchmarking abs and avg for CPU code
* Added multby7.h with another userfunc to customize it
* Wrote a CUDA kernel to test avg and multby7 optimizations generated by Aha on a GPU (link here https://colab.research.google.com/drive/15hgT4j_XmXot3FIUWmIVBsXkY7G8mEBU?usp=sharing)
